### PR TITLE
update test data

### PR DESCRIPTION
**Pull request by bernt-matthias**
for https://github.com/galaxyproject/galaxy/pull/13411

### CODE REVIEW

**Comment by mvdbeek** [comment]
That'll break old tests. Maybe put these in a subdirectory named by the galaxy version that will first use these ?

**Comment by bernt-matthias** [comment]
Can do.. Ideally we would have releases here, or?

**Comment by nsoranzo** [comment]
@bernt-matthias Should this be reverted? It doesn't seem used in the linked PR.

**Comment by bernt-matthias** [comment]
Indeed: https://github.com/galaxyproject/galaxy-test-data/pull/25

**Pull request merged**
