### PR TITLE
Add comments and empty lines to gtf filter

### PR DESCRIPTION
**Pull request by ccedmendoza**
This goes with [galaxyproject/galaxy PR #8369](https://github.com/galaxyproject/galaxy/pull/8369)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Hey @bgruening @mvdbeek @jmchilton can we savely merge this? Or should we even add comment and empty lines to the other gtf files in the repo?

`find . -iname "*gtf"`: 

```
./cufflinks_out1.gtf
./gtf2bedgraph_in.gtf
./gtf_filter_by_attribute_values_list_in2.gtf
./gtf_filter_by_attribute_values_list_out1.gtf
./gtf_filter_by_attribute_values_list_out2.gtf
./cuffcompare_in1.gtf
```

Then we can test this: https://github.com/galaxyproject/galaxy/pull/8369 and maybe the other gtf processing tools in the Galaxy core repo.

**Comment by mvdbeek** [comment]
This would break tests on older releases (for now). It might make more sense to mirror the branches found in the galaxy repo.

**Comment by jmchilton** [comment]
I'd just copy the files with new names and change the tests?

**Comment by bernt-matthias** [comment]
@ccedmendoza could you change this such that we leave the original files, but create copies where we add comments. I think this will then be accepted. 

The filenames in https://github.com/galaxyproject/galaxy/pull/8369 need to be adapted accordingly.

**Comment by bernt-matthias** [comment]
Does someone know if its possible to execute the tests in galaxy against a branch of the test-data repo?

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
